apiVersion: v1
name: spark-history-server-kubeflow
version: 0.1.0
appVersion: 2.4.0
description: A Helm chart for Spark History Server that it is integrated with Kubeflow, S3 and IRSA
keywords:
- spark
- history-server